const IndexException = Exception >> {
	out const Exception = Exception(message, cause);
}

const Array = class [T]{
	const ref : Ref[T],
	const length : U16
} => {
	called const get = (index : U16) ? IndexException => {
		if(index < 0) throw IndexException("Index cannot be negative.");
		if(index >= length) throw IndexException("Index cannot be greater than or equal to length.");
		return *(ref + index);
	}

	called const set = (index : U16, value : T) ? IndexException => {
		const previous = this(index);
		*(ref + index) = value;
		return previous;
	}
}